name: CI

on:
  push:
    branches: [ '*' ]
    pull_request:
      branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build
        run: |
          docker build -t riscv-gcc:12.2.0 -f Dockerfile .
